version: '3'
services:
  api:
    build: .
    image: api
    environment:
     - NODE_ENV=development
    network_mode: service:db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: shantsimonian
      POSTGRES_PASSWORD: shantsimonian
      POSTGRES_DB: malware_data
    ports:
     - "5432:5432"
     - "3000:3000"
    volumes:
     - ./malware_data.sql:/docker-entrypoint-initdb.d/malware_data.sql
