version: '3'
services:
  api:
    build: .
    image: api
    environment:
     - NODE_ENV=production
    network_mode: service:db
  db:
    build: ./db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: shantsimonian
      POSTGRES_PASSWORD: shantsimonian
      POSTGRES_DB: malware_data
    ports:
     - "5432:5432"
     - "3000:3000"
